/****************************************************************************
** Form implementation generated from reading ui file 'aboutform.ui'
**
** Created: Thu Oct 7 08:49:10 2004
**      by: The User Interface Compiler ($Id: aboutform.cpp,v 1.1 2004/10/20 16:36:39 jtrent Exp $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#include "aboutform.h"

#include <qvariant.h>
#include <qpushbutton.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qtooltip.h>
#include <qwhatsthis.h>
#include <qimage.h>
#include <qpixmap.h>

#include "aboutform.ui.h"
static const char* const image0_data[] = { 
"77 80 740 2",
"cu c #006d40",
"#B c #006e3f",
"ei c #006e40",
"bi c #006e41",
"em c #006e42",
".W c #006f3f",
"#N c #006f40",
".o c #006f41",
".D c #006f42",
"gq c #007040",
"#3 c #007041",
".j c #007042",
"#r c #007043",
"aq c #007143",
"g5 c #016c40",
"is c #016c42",
"i2 c #016d41",
"i7 c #016d42",
"gr c #016e3f",
"ec c #016e40",
"fb c #016e41",
"aB c #016e42",
"eT c #016f41",
"aA c #016f42",
"cr c #016f43",
"aI c #017040",
"iM c #017042",
"#A c #017043",
"#b c #017044",
"gg c #026b40",
"gW c #026c41",
"ap c #026d42",
"aT c #026e41",
"#X c #026e42",
"#c c #026f42",
"eO c #026f43",
".E c #027042",
"fT c #036c42",
"jE c #036d41",
"eh c #036d42",
"dF c #036e41",
"ah c #036e42",
"f8 c #036f41",
"bP c #037041",
"hq c #037042",
"g2 c #037044",
"cq c #037145",
"#C c #046c42",
"iW c #046e43",
"hs c #046f42",
".v c #046f43",
"gj c #047044",
".Q c #056c41",
"hh c #056f45",
"hr c #057042",
".p c #057044",
"ar c #066841",
"dE c #066f44",
"a6 c #067045",
"cI c #067244",
"c# c #067246",
"bd c #076c42",
"iS c #076d43",
"bj c #076e43",
"h6 c #077045",
"#i c #077145",
"c5 c #077146",
"ju c #077246",
"c9 c #087045",
"h# c #087146",
"gP c #087245",
"cf c #087347",
"bh c #096b43",
"eq c #096f45",
"fN c #097147",
"h. c #097248",
"cN c #097345",
"f9 c #0a6b43",
"gI c #0a7248",
"b2 c #0a7447",
"gE c #0a7448",
"gp c #0b6b43",
"eY c #0b6f46",
"hN c #0b7147",
"hc c #0c6d44",
"g1 c #0c6d47",
"cg c #0c7449",
"#a c #0d6946",
".O c #0d6c46",
"jG c #0d764b",
".I c #0e754b",
"jD c #0e774c",
".U c #0e784c",
"iT c #0f7149",
"#J c #0f744b",
".L c #0f774c",
"ce c #0f784d",
"jv c #0f794f",
"#W c #107148",
"gX c #10774b",
"hl c #10784d",
"jC c #10794f",
"jB c #107c50",
"ff c #11744c",
"bn c #11754b",
"bQ c #11754c",
"jw c #11764c",
"e6 c #126e48",
"ij c #12734b",
"hY c #12754c",
"dB c #12764d",
"b3 c #12794d",
"hp c #136748",
"iI c #13734b",
"cm c #13754b",
"ch c #13774c",
".3 c #147950",
"ca c #15754c",
"hB c #157a50",
"gQ c #166443",
"f1 c #16774f",
"df c #177a51",
"jA c #186f4b",
"#2 c #18764f",
"bo c #187951",
"hK c #187b52",
"eH c #197650",
"jx c #1a6c4b",
"in c #1b7651",
"hg c #1b7751",
"iN c #1b7852",
"hO c #1b7b53",
"b8 c #1b7b54",
"cT c #1b7d55",
"cH c #1c7451",
"be c #1c754f",
"el c #1c7953",
"ba c #1c7a54",
"bT c #1c7c56",
"cS c #1c7e56",
"eb c #1d7851",
"iE c #1d7953",
"iJ c #1d7a53",
"hA c #1d7e56",
"hy c #1d7e57",
"ed c #1e6d4c",
"f3 c #1e7c55",
"hU c #1e7d56",
".z c #1e7f57",
"cU c #1e8057",
"bJ c #1f7f58",
"gk c #1f8058",
".g c #1f8159",
"aH c #207955",
"h9 c #207e57",
"c4 c #208059",
"cV c #208159",
"bg c #217a55",
"hZ c #217d57",
"b1 c #21825b",
"io c #227b56",
"dn c #227f58",
"dk c #23805a",
"eg c #247051",
"gs c #247655",
"c8 c #24805a",
"ao c #256d4e",
"aU c #257d59",
"bX c #257d5b",
"bE c #257f5a",
"fv c #267f5b",
"gh c #26825c",
"e5 c #277554",
"b4 c #277d59",
"d4 c #287757",
"jz c #29664b",
"cR c #297a5b",
"bf c #297f5b",
"bw c #2a8560",
".J c #2b815c",
"bK c #2b8660",
".F c #2c8762",
"jy c #2d664e",
"bU c #2d7b5d",
"jm c #2d7e5d",
"eS c #2d815e",
"aJ c #2d815f",
"dW c #2d825f",
"#w c #2d8260",
"do c #2d8460",
"gJ c #2e7f5d",
".s c #2e8460",
"d. c #2e8762",
"b# c #2f7b5c",
"ac c #2f8260",
"#h c #2f8963",
"bx c #2f8a65",
"i1 c #308260",
"de c #308865",
"d# c #308965",
"c7 c #308b65",
"dg c #318060",
"bD c #318462",
"g9 c #327f5f",
"d9 c #328564",
"d3 c #338664",
"fy c #338763",
"bR c #348665",
"dV c #348764",
"dw c #348865",
"hT c #358764",
"bt c #358a68",
"d8 c #367c5e",
"iz c #367f61",
"cJ c #378464",
"i3 c #388867",
"bO c #398566",
"fu c #398769",
"dK c #398866",
"jq c #3a795e",
"#O c #3a8a68",
"eU c #3b8868",
"ab c #3c8a6a",
"fU c #3d7f64",
"hJ c #3d896a",
"d0 c #3d8c6c",
"hR c #3d906f",
"fO c #3e9171",
"aN c #3f8567",
"jb c #3f9270",
"hM c #3f9271",
"ht c #407964",
"as c #408267",
"ee c #408669",
"#T c #408f6e",
"dv c #409170",
"j# c #409372",
"jc c #409373",
"hd c #417f64",
".2 c #41886b",
"#s c #41896b",
"dA c #41916f",
"bp c #419172",
"jd c #419371",
"ef c #42886c",
"ja c #429071",
"a7 c #429170",
"je c #448e70",
"eG c #458e70",
"ds c #458f71",
"fL c #459271",
"by c #467e67",
"cM c #46866b",
"eP c #468b6f",
"gO c #468c6f",
"dp c #479071",
"cW c #48816b",
"it c #488a6e",
"#q c #49876d",
".A c #499273",
"eZ c #499375",
"dG c #499575",
"gV c #4a7b65",
".w c #4a9777",
"cl c #4b876d",
"#M c #4c9175",
"h8 c #4c9376",
"bC c #4d7d68",
"f4 c #4d9075",
"f0 c #4e8f74",
"dm c #4e9176",
".X c #4e9276",
"bm c #4e9579",
"dD c #4e9779",
"#I c #4e9b7c",
"jg c #4f9176",
"i4 c #4f9b7b",
"i0 c #4f9c7a",
"dU c #509979",
"dM c #509a7b",
"dN c #509b7d",
"dT c #509d7d",
"dL c #519d7b",
"a5 c #52987a",
"hz c #539277",
"bb c #53997c",
"ir c #54977b",
"dS c #55987e",
"az c #559a7d",
"aY c #559b7b",
"er c #57957c",
"aS c #579d81",
"iR c #589e81",
"h5 c #59a083",
"iA c #5a997e",
"ag c #5a9b80",
"eD c #5b9d82",
"iZ c #5c9880",
"e7 c #5c9c80",
"hW c #5c9c81",
"iU c #5da285",
"gY c #5e9780",
"fg c #5ea487",
"cd c #5f9880",
"fo c #5fa588",
"fn c #60a387",
"aC c #61a288",
"aV c #62a389",
"#v c #639d86",
"fc c #63a387",
"cv c #659782",
".t c #66a48b",
"bI c #679e86",
"a1 c #679f88",
".q c #67a78d",
"co c #689d87",
"iD c #689f87",
"f7 c #699c86",
"dj c #699d88",
"eN c #69a38b",
"e4 c #69a88e",
"ep c #6aa98f",
"i5 c #6b9e8a",
"ik c #6ba28d",
"#1 c #6bac93",
"hi c #6ca48d",
"eE c #6ca48e",
".k c #6ca58d",
"ii c #6cab91",
"e3 c #6cab92",
"gL c #6d9e8a",
"cO c #6da38d",
"d2 c #6da48d",
".4 c #6da48e",
"iH c #6da992",
"e8 c #6dac92",
".V c #6ea38e",
"fz c #6ea48e",
"ib c #6eab93",
"ih c #6faa92",
"iK c #6fab94",
"ez c #70a28b",
"hS c #70a68f",
"e9 c #70aa93",
"aX c #71a991",
"b9 c #729f8d",
"#z c #72a18e",
".m c #72a991",
"e2 c #72a993",
"aK c #73ac94",
"jH c #74a893",
"bF c #75a693",
"aO c #76a792",
"gi c #77a592",
"#Y c #78ac97",
"fp c #79a392",
".M c #7aa895",
"h4 c #7aaa96",
"an c #7aac98",
"fa c #7aad96",
"iQ c #7baa96",
"iv c #7bb69e",
"bY c #7caa95",
"iy c #7cb59c",
"fS c #7da593",
"ix c #7db49d",
"iw c #7db59f",
".h c #7eaf9a",
"eI c #7eb49e",
"iu c #7eb69f",
"im c #7eb6a0",
"ad c #7fb49e",
"#7 c #7fb8a2",
"bL c #80ac9a",
"#S c #80ae9b",
"eR c #80b5a0",
"eM c #81b3a0",
"#6 c #81b5a0",
"dZ c #84ad9d",
"bu c #84ae9c",
"#8 c #85b1a0",
"hm c #86b19e",
"dO c #879791",
"gw c #87a499",
"hP c #87b2a1",
"hC c #88b09f",
"eF c #88b6a4",
"at c #88b9a5",
"cp c #89aa9b",
"#V c #89bca6",
"g3 c #8aae9f",
"iV c #8ab4a2",
"eX c #8ab8a4",
"bz c #8b9b92",
"g4 c #8baea0",
"ia c #8bafa0",
"c0 c #8bb1a1",
"e0 c #8bb4a4",
"hV c #8bb5a3",
"aa c #8bb6a3",
"ha c #8cb4a4",
"dx c #8db3a2",
"h7 c #8db5a5",
"h0 c #8db8a6",
"eA c #8dbca9",
"aG c #8ebeab",
"am c #8ebfab",
"bs c #8fb3a3",
"i8 c #8fb6a5",
"a8 c #8fb7a7",
"al c #8fc0ab",
"ev c #8fc0ac",
"au c #90bfac",
"e. c #91b6a5",
"hx c #91b7a6",
"dR c #939e99",
".G c #93bdab",
"i. c #94baab",
"dJ c #94bbac",
"gZ c #95b2a8",
"fM c #95b9ab",
"#D c #95bdac",
"ci c #96b5a8",
"h1 c #96b8aa",
"fm c #98ada3",
"ip c #98bfae",
"d5 c #99c2b1",
"af c #9abeb0",
"d7 c #9bc4b2",
"bB c #9caba3",
"## c #9cb7aa",
"a0 c #9dbfb1",
"c. c #9dbfb2",
"aP c #9dc4b6",
"ea c #9dc5b4",
"c1 c #9ebeb2",
"bc c #9ebfb1",
"gH c #9ec0b2",
"d6 c #9ec8b7",
"c6 c #9fbbaf",
".i c #9fc0b2",
"iF c #9fc4b6",
"#L c #9fc9b8",
"#5 c #a0b5ac",
"aZ c #a0beb2",
"eC c #a0c0b3",
"#P c #a0c5b6",
"iO c #a0c6b7",
"ft c #a0c7b7",
"gR c #a1a8a3",
"fe c #a1beb3",
"ai c #a2c0b4",
"jF c #a2c2b5",
"ey c #a2c5b6",
".x c #a4c2b6",
"aD c #a4c3b7",
"fF c #a5c2b6",
"ex c #a6b9b2",
"gD c #a8bdb3",
"gf c #a8bfb3",
"fE c #a8c6b9",
"fG c #a9d0c1",
".T c #aac2b6",
"dH c #aac2b9",
".f c #aac7bb",
"jt c #abb9b3",
"gl c #abc0b6",
"gM c #abc3ba",
"es c #abc5bb",
"hk c #abc7ba",
"fH c #abd0c2",
"ig c #acbfb7",
"ew c #acc8bb",
"b. c #accfc1",
"dC c #adc5bb",
"#d c #adc7bc",
"fC c #adccbf",
"fI c #adcfc1",
"fD c #adcfc2",
"hQ c #aec5bb",
"fd c #aec8be",
"dX c #aecec2",
"fJ c #aed1c3",
"cc c #afafaf",
"bk c #afcabe",
"#y c #afd1c4",
"b7 c #b0cabf",
"fB c #b0d0c3",
"eK c #b1c2bb",
"a2 c #b1d0c3",
"j. c #b3bfba",
"b0 c #b3cac2",
"g. c #b3cbc0",
"ay c #b3ccc2",
"iB c #b3cfc5",
".r c #b3d0c3",
"i# c #b4ccc2",
"eu c #b5c9c0",
"iq c #b5d0c5",
"eV c #b5d1c6",
"bA c #b6bbb7",
"aW c #b7cfc5",
"f# c #b7d0c7",
"#Z c #b7d2c7",
"ej c #b7d3c8",
"ho c #b8c5c0",
"#9 c #b9c7c1",
"fP c #baccc4",
"fV c #bad8ca",
"#p c #bad8cc",
"ak c #bbcfc6",
"eo c #bbd0c8",
"#t c #bcd8cd",
"#g c #bdc8c3",
"#o c #bdd9cf",
"du c #bec9c4",
"f. c #becdc6",
"fZ c #bed8cd",
"fR c #bed8ce",
"ic c #c0cbc6",
"hL c #c0cfc8",
"da c #c1cfc9",
"fW c #c1d8ce",
"c3 c #c2d0ca",
"#n c #c2d8d0",
"cs c #c4cac6",
"#U c #c4d7cf",
"dP c #c5c5c5",
"bW c #c5c9c7",
"jk c #c5d7ce",
"jf c #c6cfcb",
"dt c #c6d2cb",
"#H c #c6d7cf",
"cQ c #c8cecb",
"fK c #c8d8d1",
"ct c #c9d2ce",
"fh c #c9d9d2",
"#E c #c9dcd4",
"dQ c #cacaca",
".R c #cad5d1",
"dh c #cbdfd7",
"#. c #cbe0d7",
"eJ c #ccd8d3",
"hX c #ccd9d3",
"dy c #ccded7",
".6 c #cce0d8",
"iG c #cddad4",
"go c #cddcd5",
"#x c #cddcd6",
"jh c #cde1d9",
".7 c #cedfd7",
".8 c #cedfd8",
".9 c #cee0d9",
"ge c #cee3da",
"cw c #cfd0cf",
"h2 c #cfd7d3",
"br c #cfe1da",
"hF c #cfe4db",
"hH c #cfe4dc",
"g6 c #d0d8d5",
"f6 c #d0e1da",
"hG c #d0e4db",
"dz c #d1ddd7",
"hb c #d2d9d5",
"gU c #d3dbd8",
"gF c #d3ddd9",
"#0 c #d3deda",
"hE c #d3e2dc",
"iL c #d4dcd9",
"iC c #d4e2dc",
"gb c #d5e5de",
"eW c #d6e1dd",
"aM c #d6e3df",
"g# c #d6e4de",
"aQ c #d7e2de",
"hu c #d7e5df",
"dd c #d8dcda",
"aR c #d9e2de",
"gt c #d9e7e2",
"cn c #dae0dd",
"il c #dae1dd",
".Y c #dceae4",
"#K c #dde4e1",
"hI c #dde6e2",
"gx c #deece6",
"cA c #dfdfdf",
"aF c #dfe8e3",
"fQ c #dfe9e5",
"#e c #dfeae6",
"gC c #dfece7",
"gy c #dfede7",
"bq c #e0e5e3",
"hn c #e0ece7",
"eL c #e2e4e2",
"cb c #e2e4e4",
"ek c #e2e6e4",
"av c #e2e7e4",
"eB c #e2e9e7",
"gz c #e2ebe7",
"bl c #e2ebe8",
"bG c #e2ece7",
"f2 c #e3e7e4",
"fA c #e3e8e6",
"fq c #e4e4e2",
"jl c #e4eeea",
"bV c #e5e6e6",
"e1 c #e5e8e6",
"b6 c #e5ecea",
"c2 c #e5efeb",
"cz c #e7e7e7",
"hv c #e7efec",
"aL c #e8ebea",
"dI c #e8edeb",
"b5 c #e9eaea",
"dY c #e9edeb",
".5 c #e9eeeb",
"gB c #e9eeec",
"iX c #e9efec",
"cK c #e9f0ee",
"db c #eaebea",
"g0 c #eaebeb",
"a9 c #eaedeb",
"ae c #eaedec",
"gc c #eaeeed",
"eQ c #ebeeec",
"hf c #ebefed",
"a4 c #ebf1ee",
"ck c #ebf2f0",
"cx c #ebf3f0",
"#4 c #eceded",
"fw c #ecefed",
"jn c #ecf0ee",
"gn c #edf3f1",
"gK c #edf4f1",
"gT c #edf4f2",
".P c #eeeeee",
"dq c #eef0ef",
"e# c #eef2f1",
"gS c #eef4f2",
"g7 c #efeff0",
".K c #eff0ef",
"#m c #eff1f0",
"cB c #f0f0f0",
"fs c #f0f2f1",
"bZ c #f0f2f2",
"jo c #f0f5f4",
"cG c #f1f0f0",
"iY c #f1f2f2",
"#Q c #f1f3f2",
"cE c #f1f4f2",
"di c #f1f5f3",
"ga c #f2f2f2",
"fY c #f2f3f2",
".B c #f2f4f3",
"gd c #f3f4f3",
"#u c #f3f4f4",
".u c #f3f5f4",
"gN c #f3f8f7",
"gA c #f4f4f4",
"cD c #f4f5f4",
"he c #f4f6f4",
"gu c #f4f6f5",
"cF c #f5f5f5",
"bN c #f5f7f6",
"fl c #f6f6f5",
"hD c #f6f6f6",
"fX c #f6f7f6",
"iP c #f6f8f7",
".S c #f6f8f8",
"cX c #f7f3f4",
"d1 c #f7f7f6",
"a3 c #f7f7f7",
"gv c #f7f9f8",
"f5 c #f7f9f9",
"g8 c #f7faf9",
"dl c #f8f6f7",
"dr c #f8f8f8",
"jr c #f8f9f9",
"bH c #f8fafa",
"#R c #f8fcfa",
"fk c #f9f6f7",
"a. c #f9f8f8",
".Z c #f9f9f9",
"cC c #f9faf9",
"jp c #f9fafa",
"gG c #f9fafb",
"a# c #f9fbfb",
"cP c #f9fcfb",
"ie c #f9fdfc",
"i6 c #faf8f9",
"dc c #faf9fa",
"et c #fafafa",
".a c #fafbfa",
"cj c #fafbfb",
"js c #fafbfc",
".b c #fafcfb",
"fx c #fafcfc",
"cY c #fafdfd",
"fj c #fbf8f9",
".1 c #fbfafb",
"cy c #fbfbfa",
"ax c #fbfbfb",
".H c #fbfbfc",
"if c #fbfcfa",
"cL c #fbfcfb",
"#G c #fbfcfc",
"cZ c #fbfcfd",
"h3 c #fbfdfd",
"gm c #fbfdfe",
".c c #fcfafb",
"hw c #fcfafc",
".# c #fcfbfb",
"bM c #fcfbfc",
".y c #fcfcfc",
"aj c #fcfcfd",
"i9 c #fcfdfc",
"#f c #fcfdfd",
".C c #fcfefd",
"en c #fcfefe",
"fr c #fdfafb",
"hj c #fdfbfc",
"aw c #fdfbfd",
"bv c #fdfcfc",
"bS c #fdfcfd",
".N c #fdfdfd",
"#F c #fdfdfe",
".n c #fdfefd",
".d c #fdfefe",
"jj c #fef9fa",
"id c #fefbfc",
"fi c #fefcfd",
"#k c #fefdfd",
"#l c #fefdfe",
".l c #fefefe",
".e c #fefeff",
"aE c #feffff",
"ji c #fffbfc",
"#j c #fffefe",
".0 c #fffeff",
"Qt c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.#.a.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.c.d",
".e.f.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.h.d",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.m.n",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.p.q.r.n",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.s.t.u.lQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.v.w.x.yQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.z.A.B.CQtQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.D.E.F.G.H.lQtQtQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.I.J.K.lQtQtQtQtQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.D.L.M.NQtQtQtQtQtQtQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.O.P.N.lQtQtQtQtQtQtQtQtQt",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.Q.R.S.l.lQtQtQtQtQt.l.H.T.U.V.l",
".e.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.W.X.Y.Z.0QtQtQtQtQtQt.l.1.2.3.j.4.l",
".l.5.6.7.8.9#.###a#b.D.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j#c#d#e.l.lQtQtQtQtQtQt#f#g#h#i.j.j.4.l",
"#j#k#l#k#l.l#k#m#n#o#p#q#r.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j#s#t#u.lQtQtQtQtQtQtQt.y#v#w.o.j.j.j.4.l",
"QtQtQtQtQtQtQtQt.l.l.N#x#y#z#A#r.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j#B#C#D#E#F.lQtQtQtQtQt.l#G#H#I#J.D.o.j.j.j.4.l",
"QtQtQtQtQtQtQtQtQtQtQtQt.0#K#L#M#N.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o#O#P#Q.lQtQtQtQtQtQt.l#R#S#T.j.j.j.j.j.j.j.4.l",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.l#U#V#W.D.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o#X#Y#Z#lQtQtQtQtQtQtQt.N#0#1#2#3.j.j.j.j.j.j.j.4.l",
"QtQtQtQt.l#4#5#6#7#7#8#9a..lQt.la#aaab.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jacadae.lQtQtQtQtQtQtQt#lafag#r.o.j.j.j.j.j.j.jahai.l",
".lajakalamanaoapaq#rarasatamauavawaxayazaA.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.DaBahaCaD.y.lQtQtQtQtQtaE.daFaGaH.j.j.j.j.j.j.j#3aIaJaKaL.l",
".laMaN.o.j.j.j.j.j.j.j.j.j.jaBaOaPaQ.laRaSaT.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.oaUaVaeaEQtQtQtQtQtQt.l#faWaX.D.j.j.j.j.j.j.j.DaTaYaZ.lQtQt",
".0a0.o.j.j.j.j.j.j.j.j.j.j.j.j.j.Da1a2a3a4a5a6.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.Da7a8.CQtQtQtQtQtQtQt.la9b.b#.j.j.j.j.j.j.j.j.DbabbaL.lQtQtQt",
".0bc#3.j.j.j.j.j.j.j.Dbdbebfbgbhbi.objbkbl.1bmbn.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jbobpbq.dQtQtQtQtQtQtQt.lbrbs.o.j.j.j.j.j.j.j.oaBbtbubvQtQtQtQtQt",
".0bc#3.j.j.j.DahbwbxbxbybzbAbBbCbDbxbxbEbFbGbHbIbJ.j#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j#3aAbKbLbM.lQtQtQtQtQt.l.lbN.6bObP#3.j.j.j.j.j.j.obQbR#KbS.lQtQtQtQtQt",
".0bc#3.j.j.obTbUbVQtQtQtQtQtQtQtQtQt.lbWbXbYbZ.db0b1b2.j.j.j.j.j.j.j.j.j.j.j.j.j.o.ob3b4b5QtQtQtQtQtQtQt.l.Nb6b7.j.j.j.j.j.j.j.j.j.ob8b9.NQtQtQtQtQtQtQtQt",
".0c..D.jc#cacb.lQtQtQtQtQtQtQtQtQtQtQtQt.laxcc.dQtbScdcecf.j.j.j.j.j.j.j.j.j.D.Dcgchci.NQtQtQtQtQtQtQt.lcjckcl.o.j.j.j.j.j.j.j.jc#cmcnaEQtQtQtQtQtQt.l.l.l",
".0c..D#rcobS.lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.laxcpcq.j.j.j.j.j.j.j.jcrahcs#f.lQtQtQtQtQtQtQtQt.nctcu.D.j.j.j.j.j.j.j.j#bcv#f.lQtQtQtQtQtQtQt.lax.l",
".lcwcxcy.lQtQtQtQtQtQtQtQtQtQtQt.lczcAcB.lQtQtQtQtQtQtQt.l.l.l.lcCcDcEcF.y.l.l.lQtQtQtQtQtQtQtQt.lcGcHcI#3.j.j.j.j.j.j.j.DcJcKcL.lQtQtQtQtQtQtQt.lcMcNcO.d",
".l.Z.l.lQtQtQtQtQtQt.lcPcQcR.g.g.gcScTcU.g.gcVcWcXcY.lQtQtQtQtQtQt.l.l.lQtQtQtQtQtQtQtQtQtQt.lcZc0cUaA#3.j.j.j.j.j.j.j#Ac1c2.l.lQtQtQtQtQtQtajc3c4c5.o.4.l",
"QtQtQtQtQtQtQtQt.l#fc6c7c8#X.D.j.j.j.j.j.j.j.Dc9d.d#da.yQt.ldbdc.lQtQtQtQtQtQtQtQtQtQtQt.l.Ndddedf.j.j.j.j.j.j.j.j.odgdhdi.lQtQtQtQtQtQt.lbMdjdk.D.j.j.4.l",
"QtQtQtQtQtQtQtQtdldmdn.j.j.j.j.j.j.j.j.j.j.j.j.j.o.Ddodpdq.ldr.Rdsdt.d.lQtQtQtQtQtQtQt.Ndudvdw.D.j.j.j.j.j.j.j.oapdxdy.NQtQtQtQtQtQtQt.ldzdAdB.D.j.j.j.4.l",
"QtQtQtQtQtQt.ldCdDdE#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.odFdGdH.ldIdJdKdLdMdNdOdPdQdRdSdTdUdV.D.o.j.j.j.j.j.j.j.jdWdXdY.lQtQtQtQtQtQtQt#ldZd0.o.j.j.j.j.j.4.l",
"QtQtQt.l.Nd1d2d3bi.j.j.j.j.j.j.j#r.jd4d5#L#L#L#L#L#Ld6d7d8d9e..He#eaebec.Dedeeefegeh.jei.j.j.j.j.j.j.j.j.oei#Yej.N.lQtQtQtQtQt.l.NekaCelem.j.j.j.j.j.j.4.l",
"QtQtQteneoepeq.j.j.j.j.j.j.j.j.oeramesetQtQtQtQtQtQt.laxeuevewexbS.yeyezap.D.j.j.j.j.j.j.j.j.j.j.j.j.j#XcJeAeBaEQtQtQtQtQtQtQt.NeCeDaB.j.j.j.j.j.j.j.DeE.N",
"Qt.la.eFeG.j.j.j.j.j.j.j.j.DeHeIeJ.lQtQtQtQtQtQtQtQtQtQtQt.l.aeK.NQt.leLeMeNeh.o.j.j.j.j.j.j.j.j.DeOePadb7.N.lQtQtQtQtQtQtQteQeReS.j.j.j.j.j.j.j.jeTeUeV.N",
".leWeXeYbi.j.j.j.j.j.j.j.jeZe0.y.lQtQtQtQtQtQtQtQtQtQtQtQtQtQt.l.lQtQt#j#ke1e2e3e4e5bi.j.j.De6e7e8e9f..y.lQtQtQtQtQtQtQt.lf#faaB.j.j.j.j.j.j.j.jfbfcfd#l.l",
".lfeeT.j.j.j.j.j.j.j.offfgfhfiaEQtQtQtQtQtQtQt.l.Nbv#Ffjfk#f.d.N.l.lQtQtQt.lbS.HflfmfnfofofofpfqcLfr.dQtQtQtQtQtQtQt.Nfsftfuec.o.j.j.j.j.j.j#3fvfnfwfxaEQt",
".0bc#3.j.j.j.j.j.D.Dfyfz.yQtQtQtQtQtQtQtQt.lfAfBb.fCfDfEfFfGfHfIfJfK#f.lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.l.l#xdJap.j.j.j.j.j.j.j.oaAfLfM#fQtQtQtQt",
".0bc#3.j.j.j.j.DfNfOfP.yQtQtQtQtQtQtQt.lfQfRfSfT.D.j.j.j.j.j.j.jaqfUfVfWfX.lQt.lax.lQtQtQtQtQtQtQtQtQtQtQtQtQt.lfYfZf0.j.j.j.j.j.j.j.j.of1a7f2.lQtQtQtQtQt",
".0bc#3.j.j.j.Df3f4f5.lQtQtQtQtQtQtQtaxf6f7f8.o.j.j.j.j.j.j.j.j.j.j.j#Nf9g.g#.N.Ngagbgc.lQtQtQtQtQtQtQtQtQtQtgdgegfgg.D.j.j.j.j.j.j.j.DghgibSQtQtQtQtQtQtQt",
".0bc#3.j.Dgjgkglgm.NQtQtQtQtQtaE.lgngogpgq.j.j.j.j.j.j.j.j.j.j.j.j.j.j.Dgrgsgtgugv#sgwgxgygzgA#k.l.laxgBgCgygD.Eeh.j.j.j.j.j.j.j.jgEc4gFgG.lQtQtQtQtQtQtQt",
".0gH.j.jgIgJdrQtQtQtQtQtQtQt.l#fgKgL.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jaAgMgN#lgOgP.ogQgRaLgSgTgUgVgW.j.j.j.j.j.j.j.j.j.j.ogXgY.NQtQtQtQtQtQtQt.l.l.l",
".0gH.j.jgZ.dQtQtQtQtQtQtQtQt.Ng0g1.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jg2g3#l.lg4.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jg5g6.dQtQtQtQtQtQtQtQt.N.y.N",
".eg7cK.N.lQtQtQtQtQtQtQtg8g9h.ei.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.Dh#ha.N.Ne#hbhc.j.j.j.j.j.j.j.j.j.j.j.jhdcKhe#F.lQtQtQtQtQtQt.lhfhghhhi.l",
".e.N.l.lQtQtQtQtQt.lhjhk.ggj.D.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.Dhlhm.H.Naxhngyhohphq#3hr#3hsg2hthugyhv.l.l.lQtQtQtQtQt.lhwhxhyaA.D.4.l",
"QtQtQtQtQtQtQtQt#j.#hzhA.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jhBhC.N.lQtQthDhEhFhFhGhFhGhHhI.NQtQtQtQtQtQtQtQtQt.lcFhJhK.D.j.j.4.l",
"QtQtQtQtQtQtQt.NhLhMhN.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jhOhP.N.lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#fhQhR.v.j.j.j.j.4.l",
"QtQtQtQtQtQt.yhShT.D.D.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j#3hUhV.NQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQthehW.s.D.j.j.j.j.j.4.l",
"QtQtQtaE#FhXfghY#N.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jhZh0aj.Nh1h2h3.N.lQtQtQtQtQtQtQt.Naweth4h5h6#3.j.j.j.j.j.j.4.l",
"QtQt.lajh7h8.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jh9i..yi#iae8ibic.Nidie.y.y.#ifigihiiij.D.j.j.j.j.j.j.j#Nik.l",
"Qt.lilimin.D.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jioip#Giqirisitiuadiviwiwixiyizfb.j.j.j.j.j.j.j.j.jcriAiB.l",
".liCiD.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.oiEiF.NiGiHiI#3.j.j#r.j.j.j.j.j.j.j.j.j.j.j.j.jiJiKiL.NQt",
".lbciM.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.oiNiOiPetiQiRiS#3.j.j.j.j.j.j.j.j.j.j.j.oiTiUiVhj.l.lQt",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jiWeyiX.liYiZi0i1.j.oaB.j.j.j.j.ji2i3i4i5i6QtQtQtQtQt",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.oi7i8g#.N.li9j.j#dAjajbjbjbjcjdjejf#fQtQtQtQtQtQtQt",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jjgjhcC.lQtQt.l#ljijjbM.d.lQtQtQtQtQtQtQtQtQtQt",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jbdjkjl.l.lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".0bc.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jjmjnjo.l.lQtQtQtQtQtQtQtQtQtQtQt.l.ljp.l",
".0bc.o.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.jiMjqjr.NQtQtQtQtQtQtQtQtQtQtQt.ljsjt.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.DjujvjwhljxjyjzjAjBjCjDaA.D.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.o.jfbehjEfb.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0gH.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".0bc#3.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.4.l",
".ljFjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjGjH.N"};


/*
 *  Constructs a aboutForm as a child of 'parent', with the
 *  name 'name' and widget flags set to 'f'.
 *
 *  The dialog will by default be modeless, unless you set 'modal' to
 *  TRUE to construct a modal dialog.
 */
aboutForm::aboutForm( QWidget* parent, const char* name, bool modal, WFlags fl )
    : QDialog( parent, name, modal, fl ),
      image0( (const char **) image0_data )
{
    if ( !name )
	setName( "aboutForm" );
    setSizePolicy( QSizePolicy( (QSizePolicy::SizeType)5, (QSizePolicy::SizeType)5, 0, 0, sizePolicy().hasHeightForWidth() ) );
    setMinimumSize( QSize( 360, 340 ) );
    setMaximumSize( QSize( 500, 500 ) );
    setPaletteBackgroundColor( QColor( 255, 255, 255 ) );
    aboutFormLayout = new QGridLayout( this, 1, 1, 11, 6, "aboutFormLayout"); 

    layout6 = new QVBoxLayout( 0, 0, 6, "layout6"); 

    layout5 = new QVBoxLayout( 0, 0, 6, "layout5"); 

    layout4 = new QHBoxLayout( 0, 0, 6, "layout4"); 

    pixmapLogo = new QLabel( this, "pixmapLogo" );
    pixmapLogo->setPixmap( image0 );
    pixmapLogo->setScaledContents( FALSE );
    layout4->addWidget( pixmapLogo );

    lblUSGS = new QLabel( this, "lblUSGS" );
    lblUSGS->setPaletteForegroundColor( QColor( 9, 111, 40 ) );
    QFont lblUSGS_font(  lblUSGS->font() );
    lblUSGS_font.setFamily( "Arial" );
    lblUSGS_font.setPointSize( 20 );
    lblUSGS_font.setBold( TRUE );
    lblUSGS->setFont( lblUSGS_font ); 
    lblUSGS->setAlignment( int( QLabel::WordBreak | QLabel::AlignVCenter ) );
    layout4->addWidget( lblUSGS );
    layout5->addLayout( layout4 );

    lblVersion = new QLabel( this, "lblVersion" );
    lblVersion->setPaletteForegroundColor( QColor( 9, 111, 40 ) );
    QFont lblVersion_font(  lblVersion->font() );
    lblVersion_font.setFamily( "Arial" );
    lblVersion_font.setPointSize( 18 );
    lblVersion_font.setBold( TRUE );
    lblVersion->setFont( lblVersion_font ); 
    lblVersion->setAlignment( int( QLabel::WordBreak | QLabel::AlignCenter ) );
    layout5->addWidget( lblVersion );
    layout6->addLayout( layout5 );
    QSpacerItem* spacer = new QSpacerItem( 21, 16, QSizePolicy::Minimum, QSizePolicy::Expanding );
    layout6->addItem( spacer );

    layout1 = new QVBoxLayout( 0, 0, 6, "layout1"); 

    lblDisclaim = new QLabel( this, "lblDisclaim" );
    lblDisclaim->setPaletteForegroundColor( QColor( 9, 111, 40 ) );
    QFont lblDisclaim_font(  lblDisclaim->font() );
    lblDisclaim_font.setFamily( "Arial" );
    lblDisclaim_font.setPointSize( 12 );
    lblDisclaim->setFont( lblDisclaim_font ); 
    lblDisclaim->setTextFormat( QLabel::RichText );
    lblDisclaim->setAlignment( int( QLabel::WordBreak | QLabel::AlignJustify | QLabel::AlignTop ) );
    layout1->addWidget( lblDisclaim );

    lblDisclaim_2 = new QLabel( this, "lblDisclaim_2" );
    lblDisclaim_2->setPaletteForegroundColor( QColor( 9, 111, 40 ) );
    QFont lblDisclaim_2_font(  lblDisclaim_2->font() );
    lblDisclaim_2_font.setFamily( "Arial" );
    lblDisclaim_2_font.setPointSize( 12 );
    lblDisclaim_2->setFont( lblDisclaim_2_font ); 
    lblDisclaim_2->setTextFormat( QLabel::RichText );
    lblDisclaim_2->setAlignment( int( QLabel::WordBreak | QLabel::AlignJustify | QLabel::AlignTop ) );
    layout1->addWidget( lblDisclaim_2 );
    layout6->addLayout( layout1 );

    aboutFormLayout->addLayout( layout6, 0, 0 );
    languageChange();
    resize( QSize(360, 342).expandedTo(minimumSizeHint()) );
    clearWState( WState_Polished );
    init();
}

/*
 *  Destroys the object and frees any allocated resources
 */
aboutForm::~aboutForm()
{
    // no need to delete child widgets, Qt does it all for us
}

/*
 *  Sets the strings of the subwidgets using the current
 *  language.
 */
void aboutForm::languageChange()
{
    setCaption( tr( "Disclaimer" ) );
    pixmapLogo->setText( QString::null );
    lblUSGS->setText( tr( "United States Geological Survey" ) );
    lblVersion->setText( tr( "<i>MapIMG</i> v0.0.000" ) );
    lblDisclaim->setText( tr( "MapIMG is a research-oriented project. Its source and binaries are provided with no warranty or support. <b>Use at your own risk.</b> We will, however, provide minimal technical support as time allows. We are also very interested in feedback as well as bug reports. All questions and comments may be sent to:" ) );
    lblDisclaim_2->setText( tr( "<p align=\"center\">mapimg@usgs.gov</p>" ) );
}

