//Copyright 2002 United States Geological Survey
//Released under GPL with MapIMG copyright 2003 USGS

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// MapIMG's main function generated by QT Designer
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#include <qapplication.h>
#include <qmessagebox.h>
#include <qstring.h>
#include <qfile.h>

#include "mapimgform.h"
#include "window_flags.h"

int main( int argc, char ** argv )
{
    QApplication a( argc, argv );
    mapimgForm *w = new mapimgForm( NULL, "mapimgform", false );
    w->show();

    a.connect( &a, SIGNAL( lastWindowClosed() ), &a, SLOT( quit() ) );



    //the below code block allows for autoloading an input image by command line
    //    or drap drop  usage:  MapIMG xxxx.extension   or
    //                          MapIMG xxxx.extension.info

    argc = 2;
    argv[1] = "orig_08b_u.img\0";
    if( argc > 1 )
    {
        QString fileName = argv[1];
        if( fileName.right( 5 ) == ".info" )
            fileName.truncate( fileName.length() - 5 );

        if( QFile::exists( fileName ) )
        {
             w->loadInputInfo( fileName ) ;
        }
    }

    return a.exec();
}
