# ----------------------------------------------------------
# Project generated by QMsNet v1.0.0
#    Template used:    Basic Application
#    Template version: 1.1
# ----------------------------------------------------------

TEMPLATE       = app
TARGET         = BilInterpolator
LANGUAGE       = C++
CONFIG        += qt warn_on

unix {
   UI_DIR      = .ui
   MOC_DIR     = .moc
   OBJECTS_DIR = .obj
}


SOURCES        =  \
	main.cpp