######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 6 12:07:48 2004
######################################################################
# $Id: USGSVectorOverlapTool.pro,v 1.2 2004/12/08 16:18:02 ahartman Exp $

TEMPLATE = lib
INCLUDEPATH += /work/usr/local/include/qgis .
CONFIG += plugin

# Input
HEADERS += voplugin.h voplugingui.h
SOURCES += voplugin.cpp voplugingui.cpp
