######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 6 12:07:48 2004
######################################################################

TEMPLATE = lib
INCLUDEPATH += /work/usr/local/include/qgis .

# Input
HEADERS += voplugin.h voplugingui.h
SOURCES += voplugin.cpp voplugingui.cpp
