######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 6 12:07:48 2004
######################################################################
# $Id: USGSVectorOverlapTool.pro,v 1.3 2004/12/08 18:41:17 ahartman Exp $

TEMPLATE = lib
INCLUDEPATH += /work/usr/local/include/qgis .
CONFIG += qt dll

# Input
HEADERS += voplugin.h voplugingui.h
SOURCES += voplugin.cpp voplugingui.cpp
